### ISSUE TITLE
Consider adding rj45less-server to SeaORM showcase!

### ISSUE THREAD

**Issue by billy1624** [pmnxis/rj45less-server#1]
Hey @pmnxis, feel free to submit a PR to showcase your project!
- https://github.com/SeaQL/sea-orm/issues/403

**Comment by pmnxis** [comment]
@billy1624 Hi! Thanks for let me know there's some opportunity introduce my showcase :)
I will update mine to the `sea-orm` showcase, after the code is working and add more description! :)

**Comment by billy1624** [comment]
Take your time! @pmnxis

**Comment by pmnxis** [comment]
Issue resolved in https://github.com/SeaQL/sea-orm/pull/925.
Thus close this issue.
